### ISSUE TITLE
How to with Koans?

### ISSUE THREAD

**Issue by omps** [gregmalcolm/python_koans#110]
I am sure you must not have heard this kind of question, and I assume its been pretty long for you had seen the code as well. 

I have cloned the python_koans github repository and started working on it. From the documentation what I learnt it change in the file to the appropriate value and make the test pass. 

Well it did seemed very simple at first, but once i stated to move again ahead with the koans i found that merely replacing the empty fields with the variable defined in the test solves the issue, which sounded pretty simple to me and I see there I am not learning anything new or programatic in doing such thing. Hence, I felt that may be what I am doing is not right and come to you to ask, if thats what is to be done, or shall we write any code to make it success. Please advise.

for eg.

    def test_plus_will_not_modify_original_strings(self):
        hi = "Hello, "
        there = "world"
        string = hi + there
        self.assertEqual(___ , hi)
        self.assertEqual(___ , there)

This will fail, but if I add

    def test_plus_will_not_modify_original_strings(self):
        hi = "Hello, "
        there = "world"
        string = hi + there
        self.assertEqual(hi , hi)
        self.assertEqual(there , there)

This is success. Is this what is to be done?

**Comment by gregmalcolm** [comment]
With unit tests you tend to check variables match literal values. A similar principal follows with the Koans. So in the first test you would be confirming that hi=="hello, " and there == "world". What you did was prove hi == hi which will never be wrong.

In real world unit testing these tests will continue to pass until one day the code changes and hi no longer equals "there, " and thus you know that either the code has a bug or the design of the program has changed which means the tests need updating.

These starting Koans are very simplistic but the complexity will increase as you go along.
