### ISSUE TITLE
[python3] about_iteration.py 

### ISSUE THREAD

**Issue by Ashtar** [gregmalcolm/python_koans#117]
So there's this function in about_iteration.py which is supposed to calculate a number from the Fibonacci sequence, judging from the name of the variable. But instead it just adds up the numbers in range (1,6):

    def test_iterators_are_a_type(self):
        it = iter(range(1,6))

        fib = 0

        for num in it:
            fib += num

        self.assertEqual(__ , fib)

So fib = 0 + 1 + 2 + 3 + 4 + 5 = 15

**Comment by gilmrjc** [comment]
The variable has a bad name, your right. To me the test works fine. You have a iterator and you use a for statement to iterate over it.  
```python
    for num in it:
        fib += num
``` 
Maybe changing the name from fib to sum will make this test cleaner. The fibonacci sequence doesn't use the index explicitly, and making this loop to return a fibonacci number will imply a big refactor, so I vote for changing the variable name to a better one.

**Comment by gregmalcolm** [comment]
Agreed. Anyone want to PR it?
