### ISSUE TITLE
[python2] About Iteration talks about ranges as if they were objects

### ISSUE THREAD

**Issue by jabagawee** [gregmalcolm/python_koans#121]
To be fair ranges are objects in py3k, but https://github.com/gregmalcolm/python_koans/blob/master/python2/koans/about_iteration.py#L97-L99 doesn't make sense when users are taught earlier that ranges _are_ lists at https://github.com/gregmalcolm/python_koans/blob/master/python2/koans/about_lists.py#L56.

**Comment by kjc** [comment]
In Python 2, the `range` function returns a list.  A list is, among other things, a [sequence](https://docs.python.org/2/reference/datamodel.html#the-standard-type-hierarchy) (scroll down a bit for the section labeled "Sequences").  Other examples of sequences are tuples, strings, and byte arrays.

All sequences are [iterable](https://docs.python.org/2/glossary.html#term-iterable), so "iterable sequence" is redundant, but not wrong.  The output of Python 2's `range` is an object, a list, a sequence, _and_ an iterable all at once.

**Comment by gregmalcolm** [comment]
I think the verdict is that the wording while not technically wrong could be better. My suggestion is if anyone want to improve on the wording, go ahead and send a pull request and we can discuss.
