### ISSUE TITLE
PythonKoans[pt-BR]

### ISSUE THREAD

**Issue by marioidival** [gregmalcolm/python_koans#122]
Hi @gregmalcolm 
I wonder if I can make a python koans fork and translate it.

**Comment by mswell** [comment]
I create in https://github.com/mswell/python_koans_br

**Comment by gregmalcolm** [comment]
@marioidival I'm sorry, I completely missed your request. Translations and variations are highly encouraged!

**Comment by mpirnat** [comment]
@gregmalcolm Are we keeping a list of translations or variations anywhere so that we can point people to them? If we are, I would be glad to add this.

**Comment by gregmalcolm** [comment]
@mpirnat This is the only translation I'm aware of. We should get that into the readme sometime.

**Comment by mpirnat** [comment]
Cool. I'll try to do it at some point in the near future then, unless somebody sends a PR first. :-)

--
Mike Pirnat
mpirnat@gmail.com
http://mike.pirnat.com/

**Comment by gregmalcolm** [comment]
I went ahead with the readme update. We get there in the end :)

#234

I'll close shop on this now, but to all looking through the issues, translations are always welcome!
