### ISSUE TITLE
Strange test names in about_generators.py

### ISSUE THREAD

**Issue by gotyaoi** [gregmalcolm/python_koans#127]
Two of the names of the tests in about_generators.py seem a little off. Specifically:

1. `test_coroutines_can_take_arguments`: The test here seems to have nothing to do with generators as coroutines, and additionally coroutines haven't been introduced yet. Not sure what the name should be though.

2. `test_generators_can_take_coroutines`: It seems the generator here isn't /taking/ a coroutine, but rather it is a coroutine. Perhaps something like `test_generators_are_also_coroutines`?

**Comment by gregmalcolm** [comment]
To be completely honest it's been a long, long time since I implemented these koans and I haven't done much python of late. If anyone wants to make the generator koans better, PRs are gladly accepted here. :)
