### ISSUE TITLE
Make Koans PEP8 compliant?

### ISSUE THREAD

**Issue by PMarian0** [gregmalcolm/python_koans#128]
This is not a super issue, but I noticed that there are small things (_indentations, spaces, names_) that are not PEP8 compliant. I noticed this in the Python3 folder (Had not checked the Python2 folder)

**Comment by gregmalcolm** [comment]
We've had PRs in the past to fix the PEP8 compliance but inevitably it keeps falling out of whack over time. We're always happy to take new PEP8 fix PRs.
