### ISSUE TITLE
Unused data in a test_sensei.py test (Python 2 and 3).

### ISSUE THREAD

**Issue by kjc** [gregmalcolm/python_koans#140]
Unused variable `expected` in both versions of `test_sensei.py`, in the `test_that_nothing_is_returned_as_sorted_result_if_there_are_3_shuffled_results` method.  It's a list of tuples that look like they should have been used in the assertions --- something like `self.assertEqual(expected, results)`, maybe?  I'll leave that change to someone who already knows what the intent was.

**Comment by gregmalcolm** [comment]
@kjc You have it right, `expected` is redundant. It probably lost relevance when I removed some bad tests a while back.

**Comment by noloman** [comment]
I opened a PR fixing this little issue #168
