### ISSUE TITLE
adding-progress-percentage to sensei's teachings

### ISSUE THREAD

**Issue by soejima** [gregmalcolm/python_koans#149]
Hey, @gregmalcolm and mates!

I've created a branch in my station and made a very little commit here showing the percentage of lessons done and the total of lessons right after the lessons done. 

And just wanted to know if you prefer I fork your project then you could incorporate my suggestion I added, or may I be part of the contributors of this repository to send my pull request?

Big hug!

ps: maybe I'm rebooting my technical life, starting from scratch with python development, so I wanted to give you this context and see if you take this risk ;-P

**Comment by mpirnat** [comment]
HI @soejima! Sorry it took me a while to get back to you. This sounds like a nice improvement. The best thing to do is fork the project and send a pull request so we can check out the change. Thanks! :-)
