### ISSUE TITLE
Python 3 - About Multiple Inheritance

### ISSUE THREAD

**Issue by ali-bahjati** [gregmalcolm/python_koans#150]
Hi, I'm learning python. I encounter the following problem at line 69 in koans_about_multiple_inheritance: 
`super(AboutMultipleInheritance.Nameable, self).__init__()`
doesn't make sense, because in MRO order, after "Nameable" is "object".

**Comment by gregmalcolm** [comment]
Hi! What's happening here is we're calling the base class constructor. SuperPig inherits from more than one base class, so the we need that extra `super` argument to specify which ancestor. For reference look at this:

https://docs.python.org/2/library/functions.html#super

so the line you mention should be calling `Nameable.__init__()`

That answer your question?

**Comment by ali-bahjati** [comment]
Hi! 
Based on the link you mentioned:

> Return a proxy object that delegates method calls to a parent or sibling class of type.

So it basically gives parent (in single inheritance structure) or more specifically next one in MRO order. 
I think the line that I mentioned (line 69) calls `object.__init__()`. To call `Nameable.__init__()` we should write 
`super(AboutMultipleInheritance.Animal, self).__init__()`
(I tested this using `print(super(AboutMultipleInheritance.Animal, self).here() )`)

Am I wrong?

**Comment by gregmalcolm** [comment]
That sounds right, but cards on the table, I haven't written much Python in the last 10 years, certainly not any with multiple inheritance. I'm closing to close shop on this issue, but if anyone sees reason to correct me, please do! :)
