### ISSUE TITLE
Pytest port?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [gregmalcolm/python_koans#155]
Anybody know if there is a [pytest][] port of this cool repo?

[pytest]: https://docs.pytest.org/en/latest/

**Comment by mpirnat** [comment]
I'm not aware of one; I believe the intention is for the Koans to be entirely self-contained with no additional requirements beyond this repo and a Python environment.

**Comment by gregmalcolm** [comment]
It's looking the answer is no, so will go ahead and close. Feel free fork and make a pytest flavor if it you get the urge though :)
