### ISSUE TITLE
Possible to hide the correct answer?

### ISSUE THREAD

**Issue by JamesCropcho** [gregmalcolm/python_koans#156]
Thank you for this great educational tool!

When I see failing test output like this:
```
You have not yet reached enlightenment ...
  AssertionError: '-=> FILL ME IN! <=-' != 0
```
…well, I know the answer is `0`, and for the sake of my learning, that value is hard to "un-see." Is there anyway to hide it?

**Comment by denisaltroy** [comment]
Merely my opinion...

Koans are not about getting the answer right but more about understanding the code and the results we expect the code to produce.

[Test Driven Developement](https://en.wikipedia.org/wiki/Test-driven_development) (TDD) is about testing if code works as expected by comparing code ouput to a value we know is True (the answer) so I believe removing or hiding the answers would defeat the purpose of using TDD as a way of learning.

The license leaves you free to fork and transform these Koans into a quiz once you reach enlightenment... :)

**Comment by gregmalcolm** [comment]
Yep, pretty much what @denis-roy said. :)

If the test runner was web based I think answer hiding would be a great feature, but for this version of Python Koans I think we're best sticking to our TDD roots.
