### ISSUE TITLE
Clarity and intent problems in `about_regex.py`

### ISSUE THREAD

**Issue by kjc** [gregmalcolm/python_koans#160]
I noticed that the [`about_regex.py`](https://github.com/gregmalcolm/python_koans/blob/master/python2/koans/about_regex.py) koans are at the very bottom of the "Path to Enlightenment", after even the extra credit (in the `python[23]/koans.txt` files I created, and in the test runners before them).  Was that supposed to be a hint that it's not ready for prime time?

I ran into several problems with the koans in `AboutRegex`, and I often couldn't figure out what the author's intent was.  (I gather it wasn't @gregmalcolm.)  The author credits _SAMS Teach Yourself Regular Expressions in 10 Minutes_ by Ben Forta for inspiring the module.  I don't have that book, but it might not help anyway --- presumably the koans aren't just copies of the book's examples.

I guess I'm mostly asking if the original author (Felix?) is still around, and if not, what your plan is for this module?

(I've submitted #159 to make comparing the Python 2 and Python 3 versions of `about_regex.py` easier.  Turns out, they're identical after all Python 2 fixes are applied to the Python 3 version.)

A few examples of things I want to fix (line numbers taken from the Python 2 file):

### Lines 46--52

I think the intent of `test_matching_literal_text_how_many` is for the user to replace `re.match(...)` with something like `len(re.findall(...))`.  But the assertion has the user typing something that will evaluate equal to a match object.

As written, the `__` should be replaced with `None`, which might be what the "tip" is trying to say.  But that contradicts the other comment that asks for how many times the name `'Felix'` appears, which would be a number.

    def test_matching_literal_text_how_many(self):
        ...
        string = ("Hello, my name is Felix and these koans are based " +
            "on Ben's book: Regular Expressions in 10 minutes. " +
            "Repeat My name is Felix")
        m = re.match('Felix', string)  # TIP: match may not be the best option

        # I want to know how many times my name appears
        self.assertEqual(m, __)

If the goal is to fix the function called, then the assertion should be complete:

        # I want to know how many times my name appears.
        # TIP: match may not be the best function for the job.
        matches = re.match('Felix', string)
        count = len(matches)
        self.assertEqual(count, 2)

If the goal is to fill in the assertion with `None`, then the second comment is wrong.  (Also, this koan won't teach much.)

Maybe there should be two koans, this one and something like `test_failed_matches_return_none()`?

### Line 83

There is no `myArray` variable in `test_matching_any_character`, and it doesn't occur in the string we're given to search.  What did the author mean here?

    change_this_search_string = 'a..xlx' # <-- I want to find all uses of myArray

### Lines 85--87

Making the assertion in `test_matching_any_character` pass has almost nothing to do with the `.` character or what it matches.  The real problem is the typo in the regex: `'a..xlx'` should be `'a..xls'`.

(Note that the first `.` in this regex will match a variety of digits, while the second will by chance only match periods...  This will almost certainly confuse beginners.)

### Lines 89--113

`test_matching_set_character` is looking for the wrong answer.  There are _four_ files that match, not 3.

    # I want to find all files for North America(na) or South
    # America(sa), but not (ca) TIP you can use the pattern .a.
    # which matches in above test but in this case matches more than
    # you want
    change_this_search_string = r'[nsc]a[2-9]\.xls'
    self.assertEquals(
        len(re.findall(change_this_search_string, string)),
        3)  # <----=  Should be 4, not 3.

Maybe he specifically wants only the `'1'` version of each file?  If so, then the solution is to _entirely remove_ the character set and replace it with the literal `'1'`...  which is a weird solution for the koan that introduces character sets.

Also, what "above test" is that "tip" talking about?  There was no `'.a.'` in `test_matching_any_character`.

### Lines 115--140

`test_anything_but_matching` has nothing to do with character sets, negated or otherwise...  The string `'am'` appears exactly once in the input, so there's nothing to filter out.  Once again, the solution is to _remove_ the supposed subject.

    def test_anything_but_matching(self):
        # ...
        # I want to find the name sam
        change_this_search_string = '[^nc]am'
        self.assertEquals(
            re.findall(change_this_search_string, string),
            ['sam.xls'])

The claim in the comments ("I want to find the name 'sam'") is wrong --- he wants to find exactly one filename, `'sam.xls'`, which doesn't even require a regex...  Windows' `Ctrl-F` could solve this one.

**Comment by gregmalcolm** [comment]
Thanks for cleaning this up!

**Comment by erikhuizinga** [comment]
But now I still don't know what to do with:

```python
change_this_search_string = 'a..xlx' # <-- I want to find all uses of myArray
```

**Comment by kjc** [comment]
@erikhuizinga:  For what it's worth, neither do I.  (Meaning I haven't actually _fixed_ any of these problems yet.)
