### ISSUE TITLE
Length of string

### ISSUE THREAD

**Issue by StaNov** [gregmalcolm/python_koans#164]
Hi, I'd like to ask what is the intended solution to this task:

```
    def test_use_backslash_at_the_end_of_a_line_to_continue_onto_the_next_line(self):
        string = "It was the best of times,\n\
It was the worst of times."
        self.assertEqual(__, len(string))
```

Should one count the letters one-by-one and then put there "52"?

I can't figure out any better solution.

Thanks in advance!

**Comment by gregmalcolm** [comment]
I would say anything goes as long as you have an appreciation of `len(string)` by filling in the blank. You could count chars, enter it and maybe correct if you're off by one. Or you could fire up the python command line, query `len("It was the best of times,\n\t was the worst of times.")` and give that value if you think it makes sense. You could even just guess then correct when it tells you how off you are.

**Comment by StaNov** [comment]
I counted it one-by-one and was off by one because I thought that the trailing backslash also adds a new new-line character. So I guess that's what I learnt from it :)

Thanks for your reply and for your time making this project :)
