### ISSUE TITLE
question about test_that_unittest_asserts_work_the_same_way_as_python_asserts

### ISSUE THREAD

**Issue by eliot1785** [gregmalcolm/python_koans#175]
Thanks for creating these koans. If you have the time, I'm a little curious about the difference between "unit test asserts" and "python asserts."

I just realized that you have a bunch of calls to self.assertTrue, but assertTrue isn't actually defined anywhere within about_asserts.py nor does the class in that file inherit from anything. So I can't figure out where self.assertTrue would be coming from. 

I'm guessing, though, that self.assertTrue is somehow the "unit test assert" whereas the bare assert is the Python assert. But it would be nice to get confirmation.

**Comment by kjc** [comment]
The various `About*` classes inherit from `Koan` (in [`runner/koan.py`](https://github.com/gregmalcolm/python_koans/blob/master/python3/runner/koan.py)), which inherits from the standard library's [`unittest.TestCase`](https://docs.python.org/3/library/unittest.html#unittest.TestCase).  That's where the various `self.assert*` methods come from.  Think of them as a collection of wrappers around the Python `assert` that allow more informative error messages and handy tricks like [type-specific equality testing](https://docs.python.org/3/library/unittest.html#type-specific-methods).
