### ISSUE TITLE
about_triangle_project2.py

### ISSUE THREAD

**Issue by KTatITAssist** [gregmalcolm/python_koans#176]
Hi

I have added the code into `triangle.py` - and saved it!

    def triangle(a, b, c):
        # DELETE 'PASS' AND WRITE THIS CODE
        #pass
        def triangle(a, b, c):
            if a <= 0 or b <= 0 or c <= 0:
                raise TriangleError(AttributeError('Negative edge is not allowed'))
            if a + b + c <= 2 * max(a, b, c):
                raise TriangleError(AttributeError('largest side should be smaller than sum of 2 other sides'))
            if a == b == c:
                return 'equilateral'
            elif a == b or b == c or c == a:
                return 'isosceles'
            return 'scalene'

    # Error class used in part 2.  No need to change this code.
    class TriangleError(Exception):
        pass

When I run the `contemplate_koans.py` I get the following error and I'm struggling to work out what is wrong.

I get "AssertionError: TriangleError not raised" on the line that calls triangle in `about_triangle_project2.py` the line is `triangle(0, 0, 0)`

Can you help me?

**Comment by kjc** [comment]
(I've fixed your code and text formatting.  Let me know if I damaged anything.)

It looks like you've accidentally nested a new `triangle` function inside the given `triangle` function, instead of replacing it with your own.

**Comment by KTatITAssist** [comment]
Thank you. That was the problem. Sometimes one can't see the wood for the trees!

**Comment by KTatITAssist** [comment]
Thank you for your help. That was the problem!

Kathy Turner

*KT@ITAssist*
Email: kt.itassist@gmail.com
Mobile: 07926 702 047
Website: http://kt-itassist.co.uk
