### ISSUE TITLE
Link http://bit.ly/__class__ does not work when offline, 

### ISSUE THREAD

**Issue by joanmarcriera** [gregmalcolm/python_koans#177]
Hi, your code is very nice to learn while offline, but using bit.ly makes it strange. Just using the link to the repo would be nice,

**Comment by gregmalcolm** [comment]
Fair point! Any interest in throwing us a PR to make that change?

**Comment by kolapsys** [comment]
#182 Created for this issue.

**Comment by mpirnat** [comment]
Merged, thanks @kolapsys! :-)

**Comment by kolapsys** [comment]
Glad to do it :)
