### ISSUE TITLE
f-strings in AboutStringManipulation

### ISSUE THREAD

**Issue by GabrielGLevine** [gregmalcolm/python_koans#225]
The [assertions dealing with formatting](https://github.com/gregmalcolm/python_koans/blob/master/python3/koans/about_string_manipulation.py#L8-L26) in AboutStringManipulation exclusively use the `.format()` syntax and don't make mention of f-strings. Is this an effort to keep Python3 koans compatible with Python 3 versions before 3.6?

**Comment by gregmalcolm** [comment]
I think mostly it's because the koans were originally authored 10 years ago before we Python 3.6 was a thing.

Hope that answers your question, happy to chat more if it doesn't!
