### ISSUE TITLE
[feature]: Hope only shows passed test functions in this run

### ISSUE THREAD

**Issue by xiangaoole** [gregmalcolm/python_koans#228]
In [Ruby Koan](https://github.com/edgecase/ruby_koans/blob/master/src/neo.rb#L243), the output only shows passed test functions in this run. This is implemented by saving the total passed test count in a file, and only show the new passed ones in this run.

```ruby
    def add_progress(prog) # save the passed test methods count in a file
      @_contents = nil
      exists = File.exists?(PROGRESS_FILE_NAME)
      File.open(PROGRESS_FILE_NAME,'a+') do |f|
        f.print "#{',' if exists}#{prog}"
      end
    end

    def progress
      if @_contents.nil?
        if File.exists?(PROGRESS_FILE_NAME)
          File.open(PROGRESS_FILE_NAME,'r') do |f|
            @_contents = f.read.to_s.gsub(/\s/,'').split(',') # read former passed test methods
          end
        else
          @_contents = []
        end
      end
      @_contents
    end

    def observe(step)
      if step.passed?
        @pass_count += 1
        if @pass_count > progress.last.to_i # here, only print the new passed test functions
          @observations << Color.green("#{step.koan_file}##{step.name} has expanded your awareness.")
        end
      else
        @failed_test = step
        @failure = step.failure
        add_progress(@pass_count)
        @observations << Color.red("#{step.koan_file}##{step.name} has damaged your karma.")
        throw :neo_exit
      end
    end
```

But in this Python Koan, the output shows all the passed test functions. That make the output too long.

The Ruby Koan output is cleaner: 
![008eGmZEly1gn90bauyfzj30zq0u0dnr](https://user-images.githubusercontent.com/32730253/107236991-39430e80-6a61-11eb-8591-e2a51eb5a60b.jpg)

**Comment by gregmalcolm** [comment]
Yep, the Ruby Koans presentation changed a lot in the couple of years after Python Koans was ported. For example, that fancy progress bar doo-hicky. I think Python Koans got color first. but I'll be first to admit that Ruby Koan presentational enhancements have been more flashy. For example the fancy ascii art when you complete Ruby Koans.

I have to say, I have no plans to do anything more with the presentation myself. Though we're always happy to accept cool contributions from the community
