### ISSUE TITLE
About String Manipulation -> test_raw_strings_do_not_interpret_escape_characters

### ISSUE THREAD

**Issue by Puistis** [gregmalcolm/python_koans#237]
Hi

When the answer is wrong eg.
![image](https://user-images.githubusercontent.com/57521319/117805416-a08b7d00-b261-11eb-92bd-9a35f2449349.png)
and you run the test you get 
![image](https://user-images.githubusercontent.com/57521319/117805535-bf8a0f00-b261-11eb-8f73-3b9f43ae3e25.png)

But when the answer is right
![image](https://user-images.githubusercontent.com/57521319/117805685-ef391700-b261-11eb-9caa-36d7bcf8c847.png)
and you run the tests
![image](https://user-images.githubusercontent.com/57521319/117805755-07a93180-b262-11eb-8a8c-c40303d257d8.png)
that particular test disappears from the completed list

Not really a major issue but a glitch none the less

**Comment by adnanprodev** [comment]
@Puistis - It does not actually disappear from the completed list. The completed list has the tests sorted alphabetically - and it moves a bit higher up in the list and is not shown as the last completed test. If you could post a longer screenshot or the complete text output, you would see that the test_raw_strings_do_not_interpret_escape_characters  moves to near top of the list. The AssertionErrors (in red) are sequential (the order in which they appear in the file), but the successfully completed tests (in green) are alphabetical. 

@kjc - If the response above is satisfactory, you can close this.
