### ISSUE TITLE
Koans use testing methods removed in Python 3.12

### ISSUE THREAD

**Issue by okin** [gregmalcolm/python_koans#283]
In Python 3.12 various deprecated test method names have been removed. You can find [a complete list](https://docs.python.org/3.12/whatsnew/3.12.html#id3) in the Python 3.12 changelog.

Some of these methods are used in the koans and encountering these will result in a message like the following:

```
AttributeError: 'AboutTuples' object has no attribute 'assertRegexpMatches'. Did you mean: 'assertNoRegexpMatches'?
```

Luckily the removed test names have just been aliases for other, still existing methods that can be used instead.

**Comment by hugovk** [comment]
Where exactly is this happening? Please can you paste the full traceback?

I don't see `assertRegexpMatches` used in https://github.com/gregmalcolm/python_koans/blob/master/koans/about_tuples.py or this repo. 

Some were replaced in https://github.com/gregmalcolm/python_koans/pull/130.

**Comment by okin** [comment]
This is a problem on my side. Had a fork that should have been updated to the latest version but after checking again it wasn't.

Please excuse the unnecessary noise!
