### ISSUE TITLE
Koan sequence in Python2 (trivial)

### ISSUE THREAD

**Issue by ghost** [gregmalcolm/python_koans#88]
Not a bug, more of a nitpick or cavil

In using "python2 contemplate_koans py", _test_triple_single_quotes_work_too_ (about_strings.py - line 21) is followed by _test_use_single_quotes_to_create_string_with_double_quotes_ (about_strings.py - line 29) , skipping over _test_raw_strings_are_also_strings_ (about_strings.py - line 25).

The _test_raw_strings_are_also_strings_ (about_strings.py - line 25) is then performed next.

**Comment by gregmalcolm** [comment]
We just elliminated Python2 support, so closing up on this!
